-- Create new inventory table specifically for products from completed orders
-- This table stores all products that come from completed orders in orders.php
-- This is the single source of truth for inventory - all products come from completed orders

CREATE TABLE IF NOT EXISTS `inventory_from_completed_orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL COMMENT 'ID from admin_orders or orders table',
  `order_table` VARCHAR(20) DEFAULT 'admin_orders' COMMENT 'Which table the order came from: admin_orders or orders',
  `inventory_id` INT(11) DEFAULT NULL COMMENT 'Original inventory_id from order (for reference)',
  `supplier_id` INT(11) DEFAULT NULL COMMENT 'Supplier ID from admin_orders',
  `user_id` INT(11) DEFAULT NULL COMMENT 'User ID who created the order (from admin_orders)',
  `is_automated` TINYINT(1) DEFAULT 0 COMMENT 'Whether order was automated (from admin_orders)',
  `sku` VARCHAR(50) DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `variation` VARCHAR(255) DEFAULT NULL COMMENT 'Product variation from admin_orders',
  `unit_type` VARCHAR(50) DEFAULT 'per piece' COMMENT 'Unit type from admin_orders',
  `quantity` INT(11) NOT NULL DEFAULT 0 COMMENT 'Quantity from completed order',
  `available_quantity` INT(11) NOT NULL DEFAULT 0 COMMENT 'Available stock after sales',
  `sold_quantity` INT(11) NOT NULL DEFAULT 0 COMMENT 'Total sold quantity',
  `reorder_threshold` INT(11) NOT NULL DEFAULT 0,
  `unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'Unit price from admin_orders',
  `supplier_name` VARCHAR(100) DEFAULT NULL,
  `category` VARCHAR(50) DEFAULT NULL,
  `location` VARCHAR(100) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `image_path` VARCHAR(255) DEFAULT NULL,
  `order_date` DATETIME DEFAULT NULL COMMENT 'Date when order was placed (from admin_orders.order_date)',
  `confirmation_status` ENUM('pending','confirmed','cancelled','delivered','completed') DEFAULT 'completed' COMMENT 'Order status from admin_orders',
  `confirmation_date` DATETIME DEFAULT NULL COMMENT 'Date when order was confirmed (from admin_orders.confirmation_date)',
  `completion_date` DATETIME DEFAULT NULL COMMENT 'Date when order was marked as completed',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Soft delete flag: 0 = active, 1 = deleted',
  `last_updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_order_inventory_variation` (`order_id`, `order_table`, `inventory_id`, `variation`(100)),
  KEY `idx_inventory_id` (`inventory_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_table` (`order_table`),
  KEY `idx_supplier_id` (`supplier_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_sku` (`sku`),
  KEY `idx_category` (`category`),
  KEY `idx_completion_date` (`completion_date`),
  KEY `idx_confirmation_status` (`confirmation_status`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
